# Generated by Django 3.2.4 on 2021-07-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subTotal',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
