# Generated by Django 3.2.4 on 2021-07-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210622_1814'),
        ('carts', '0002_auto_20210703_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='productos',
        ),
        migrations.AddField(
            model_name='cart',
            name='productos',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='products.product'),
            preserve_default=False,
        ),
    ]
